// This file will be auto-generated by Supabase CLI
// Run: npx supabase gen types typescript --project-id <your-project-id> > src/types/database.types.ts
// Or use: supabase gen types typescript --local > src/types/database.types.ts (for local development)

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      // Add your table types here after generating from Supabase
      // Example structure:
      // profiles: {
      //   Row: {
      //     id: string
      //     created_at: string
      //   }
      //   Insert: {
      //     id?: string
      //     created_at?: string
      //   }
      //   Update: {
      //     id?: string
      //     created_at?: string
      //   }
      // }
    }
    Views: {
      // Add your view types here
    }
    Functions: {
      // Add your function types here
    }
    Enums: {
      // Add your enum types here
    }
  }
}


